site_name: JXP
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Authentication: authentication.md
  - Schemas: schemas.md
  - Restful API: api.md
  - Roles and Permissions: permissions.md
  - Hooks: hooks.md
  - Aggregations: aggregations.md
  - Bulk Writes: bulk_writes.md
  - Queries: queries.md
  - Caching: caching.md
  - Websocket: websocket.md
  - Special Features: special.md
  - Changelog: changelog.md
theme: readthedocs